export const tarotCard = [
  {
    id: 1,
    image: require('../assets/images/tarot/tarot_a.png'),
    value: require('../assets/images/tarot/1.png'),
    name: 'The Fool',
  },
  {
    id: 2,
    image: require('../assets/images/tarot/tarot_b.png'),
    value: require('../assets/images/tarot/2.png'),
    name: 'THE MAGICIAN',
  },
  {
    id: 3,
    image: require('../assets/images/tarot/tarot_c.png'),
    value: require('../assets/images/tarot/3.png'),
    name: 'THE HIGH PRIESTESS',
  },
  {
    id: 4,
    image: require('../assets/images/tarot/tarot_d.png'),
    value: require('../assets/images/tarot/4.png'),
    name: 'THE EMPRESS',
  },
  {
    id: 5,
    image: require('../assets/images/tarot/tarot_e.png'),
    value: require('../assets/images/tarot/5.png'),
    name: 'THE EMPEROR',
  },
  {
    id: 6,
    image: require('../assets/images/tarot/tarot_f.png'),
    value: require('../assets/images/tarot/6.png'),
    name: 'THE HIEROPHANT',
  },
  {
    id: 7,
    image: require('../assets/images/tarot/tarot_a.png'),
    value: require('../assets/images/tarot/7.png'),
    name: 'THE LOVERS',
  },
  {
    id: 8,
    image: require('../assets/images/tarot/tarot_b.png'),
    value: require('../assets/images/tarot/8.png'),
    name: 'THE CHARIOT',
  },
  {
    id: 9,
    image: require('../assets/images/tarot/tarot_c.png'),
    value: require('../assets/images/tarot/9.png'),
    name: 'STRENGTH',
  },
  {
    id: 10,
    image: require('../assets/images/tarot/tarot_d.png'),
    value: require('../assets/images/tarot/10.png'),
    name: 'THE HERMIT',
  },
  {
    id: 11,
    image: require('../assets/images/tarot/tarot_e.png'),
    value: require('../assets/images/tarot/11.png'),
    name: 'WHEEL OF FORTUNE',
  },
  {
    id: 12,
    image: require('../assets/images/tarot/tarot_f.png'),
    value: require('../assets/images/tarot/12.png'),
    name: ' JUSTICE',
  },
  {
    id: 13,
    image: require('../assets/images/tarot/tarot_a.png'),
    value: require('../assets/images/tarot/13.png'),
    name: 'THE HANGED MAN',
  },
  {
    id: 14,
    image: require('../assets/images/tarot/tarot_b.png'),
    value: require('../assets/images/tarot/14.png'),
    name: 'DEATH',
  },
  {
    id: 15,
    image: require('../assets/images/tarot/tarot_c.png'),
    value: require('../assets/images/tarot/15.png'),
    name: 'TEMPERANCE',
  },
  {
    id: 16,
    image: require('../assets/images/tarot/tarot_d.png'),
    value: require('../assets/images/tarot/16.png'),
    name: 'THE DEVIL',
  },
  {
    id: 17,
    image: require('../assets/images/tarot/tarot_e.png'),
    value: require('../assets/images/tarot/17.png'),
    name: 'THE TOWER',
  },
  {
    id: 18,
    image: require('../assets/images/tarot/tarot_f.png'),
    value: require('../assets/images/tarot/18.png'),
    name: 'THE STAR',
  },
  {
    id: 19,
    image: require('../assets/images/tarot/tarot_a.png'),
    value: require('../assets/images/tarot/19.png'),
    name: 'THE MOON',
  },
  {
    id: 20,
    image: require('../assets/images/tarot/tarot_b.png'),
    value: require('../assets/images/tarot/20.png'),
    name: 'THE SUN',
  },
  {
    id: 21,
    image: require('../assets/images/tarot/tarot_c.png'),
    value: require('../assets/images/tarot/21.png'),
    name: 'JUDGEMENT',
  },
  {
    id: 22,
    image: require('../assets/images/tarot/tarot_d.png'),
    value: require('../assets/images/tarot/22.png'),
    name: 'THE WORLD',
  },
  {
    id: 23,
    image: require('../assets/images/tarot/tarot_e.png'),
    value: require('../assets/images/tarot/23.png'),
    name: 'ACE OF CUPS',
  },
  {
    id: 24,
    image: require('../assets/images/tarot/tarot_f.png'),
    value: require('../assets/images/tarot/24.png'),
    name: 'The Fool',
  },
  {
    id: 25,
    image: require('../assets/images/tarot/tarot_a.png'),
    value: require('../assets/images/tarot/25.png'),
    name: 'The Fool',
  },
  {
    id: 26,
    image: require('../assets/images/tarot/tarot_b.png'),
    value: require('../assets/images/tarot/26.png'),
    name: 'The Fool',
  },
  {
    id: 27,
    image: require('../assets/images/tarot/tarot_c.png'),
    value: require('../assets/images/tarot/27.png'),
    name: 'The Fool',
  },
  {
    id: 28,
    image: require('../assets/images/tarot/tarot_d.png'),
    value: require('../assets/images/tarot/28.png'),
    name: 'The Fool',
  },
  {
    id: 29,
    image: require('../assets/images/tarot/tarot_e.png'),
    value: require('../assets/images/tarot/29.png'),
    name: 'The Fool',
  },
  {
    id: 30,
    image: require('../assets/images/tarot/tarot_f.png'),
    value: require('../assets/images/tarot/30.png'),
    name: 'The Fool',
  },
  {
    id: 31,
    image: require('../assets/images/tarot/tarot_a.png'),
    value: require('../assets/images/tarot/31.png'),
    name: 'The Fool',
  },
  {
    id: 32,
    image: require('../assets/images/tarot/tarot_b.png'),
    value: require('../assets/images/tarot/32.png'),
    name: 'The Fool',
  },
  {
    id: 33,
    image: require('../assets/images/tarot/tarot_c.png'),
    value: require('../assets/images/tarot/33.png'),
    name: 'PAGE OF CUPS',
  },
  {
    id: 34,
    image: require('../assets/images/tarot/tarot_d.png'),
    value: require('../assets/images/tarot/34.png'),
    name: 'KNIGHT OF CUPS',
  },
  {
    id: 35,
    image: require('../assets/images/tarot/tarot_e.png'),
    value: require('../assets/images/tarot/35.png'),
    name: 'QUEEN OF CUPS',
  },
  {
    id: 36,
    image: require('../assets/images/tarot/tarot_f.png'),
    value: require('../assets/images/tarot/36.png'),
    name: 'KING OF CUPS',
  },
  {
    id: 37,
    image: require('../assets/images/tarot/tarot_a.png'),
    value: require('../assets/images/tarot/37.png'),
    name: 'ACE OF PENTACLES',
  },
  {
    id: 38,
    image: require('../assets/images/tarot/tarot_b.png'),
    value: require('../assets/images/tarot/38.png'),
    name: 'The Fool',
  },
  {
    id: 39,
    image: require('../assets/images/tarot/tarot_c.png'),
    value: require('../assets/images/tarot/39.png'),
    name: 'The Fool',
  },
  {
    id: 40,
    image: require('../assets/images/tarot/tarot_d.png'),
    value: require('../assets/images/tarot/40.png'),
    name: 'The Fool',
  },
  {
    id: 41,
    image: require('../assets/images/tarot/tarot_e.png'),
    value: require('../assets/images/tarot/41.png'),
    name: 'The Fool',
  },
  {
    id: 42,
    image: require('../assets/images/tarot/tarot_f.png'),
    value: require('../assets/images/tarot/42.png'),
    name: 'The Fool',
  },
  {
    id: 43,
    image: require('../assets/images/tarot/tarot_a.png'),
    value: require('../assets/images/tarot/43.png'),
    name: 'The Fool',
  },
  {
    id: 44,
    image: require('../assets/images/tarot/tarot_b.png'),
    value: require('../assets/images/tarot/44.png'),
    name: 'The Fool',
  },
  {
    id: 45,
    image: require('../assets/images/tarot/tarot_c.png'),
    value: require('../assets/images/tarot/45.png'),
    name: 'The Fool',
  },
  {
    id: 46,
    image: require('../assets/images/tarot/tarot_d.png'),
    value: require('../assets/images/tarot/46.png'),
    name: 'The Fool',
  },
  {
    id: 47,
    image: require('../assets/images/tarot/tarot_e.png'),
    value: require('../assets/images/tarot/47.png'),
    name: 'PAGE OF PENTACLES',
  },
  {
    id: 48,
    image: require('../assets/images/tarot/tarot_f.png'),
    value: require('../assets/images/tarot/48.png'),
    name: 'KNIGHT OF PENTACLES',
  },
  {
    id: 49,
    image: require('../assets/images/tarot/tarot_a.png'),
    value: require('../assets/images/tarot/49.png'),
    name: 'QUEEN OF PENTACLES',
  },
  {
    id: 50,
    image: require('../assets/images/tarot/tarot_b.png'),
    value: require('../assets/images/tarot/50.png'),
    name: 'KING OF PENTACLES',
  },
  {
    id: 51,
    image: require('../assets/images/tarot/tarot_c.png'),
    value: require('../assets/images/tarot/51.png'),
    name: 'ACE OF SWORDS',
  },
  {
    id: 52,
    image: require('../assets/images/tarot/tarot_d.png'),
    value: require('../assets/images/tarot/52.png'),
    name: 'The Fool',
  },
  {
    id: 53,
    image: require('../assets/images/tarot/tarot_e.png'),
    value: require('../assets/images/tarot/53.png'),
    name: 'The Fool',
  },
  {
    id: 54,
    image: require('../assets/images/tarot/tarot_f.png'),
    value: require('../assets/images/tarot/54.png'),
    name: 'The Fool',
  },
  {
    id: 55,
    image: require('../assets/images/tarot/tarot_a.png'),
    value: require('../assets/images/tarot/55.png'),
    name: 'The Fool',
  },
  {
    id: 56,
    image: require('../assets/images/tarot/tarot_b.png'),
    value: require('../assets/images/tarot/56.png'),
    name: 'The Fool',
  },
  {
    id: 57,
    image: require('../assets/images/tarot/tarot_c.png'),
    value: require('../assets/images/tarot/57.png'),
    name: 'The Fool',
  },
  {
    id: 58,
    image: require('../assets/images/tarot/tarot_d.png'),
    value: require('../assets/images/tarot/58.png'),
    name: 'The Fool',
  },
  {
    id: 59,
    image: require('../assets/images/tarot/tarot_e.png'),
    value: require('../assets/images/tarot/59.png'),
    name: 'The Fool',
  },
  {
    id: 60,
    image: require('../assets/images/tarot/tarot_f.png'),
    value: require('../assets/images/tarot/60.png'),
    name: 'The Fool',
  },
  {
    id: 61,
    image: require('../assets/images/tarot/tarot_a.png'),
    value: require('../assets/images/tarot/61.png'),
    name: 'PAGE OF SWORDS',
  },
  {
    id: 62,
    image: require('../assets/images/tarot/tarot_b.png'),
    value: require('../assets/images/tarot/62.png'),
    name: 'KNIGHT OF SWORDS',
  },
  {
    id: 63,
    image: require('../assets/images/tarot/tarot_c.png'),
    value: require('../assets/images/tarot/63.png'),
    name: 'QUEEN OF SWORDS',
  },
  {
    id: 64,
    image: require('../assets/images/tarot/tarot_d.png'),
    value: require('../assets/images/tarot/64.png'),
    name: 'KING OF SWORDS',
  },
  {
    id: 65,
    image: require('../assets/images/tarot/tarot_e.png'),
    value: require('../assets/images/tarot/65.png'),
    name: 'ACE OF WANDS',
  },
  {
    id: 66,
    image: require('../assets/images/tarot/tarot_f.png'),
    value: require('../assets/images/tarot/66.png'),
    name: 'PAGE OF WANDS',
  },
  {
    id: 67,
    image: require('../assets/images/tarot/tarot_a.png'),
    value: require('../assets/images/tarot/67.png'),
    name: 'KNIGHT OF WANDS',
  },
  {
    id: 68,
    image: require('../assets/images/tarot/tarot_b.png'),
    value: require('../assets/images/tarot/68.png'),
    name: 'The Fool',
  },
  {
    id: 69,
    image: require('../assets/images/tarot/tarot_c.png'),
    value: require('../assets/images/tarot/69.png'),
    name: 'The Fool',
  },
  {
    id: 70,
    image: require('../assets/images/tarot/tarot_d.png'),
    value: require('../assets/images/tarot/70.png'),
    name: 'The Fool',
  },
  {
    id: 71,
    image: require('../assets/images/tarot/tarot_e.png'),
    value: require('../assets/images/tarot/71.png'),
    name: 'The Fool',
  },
  {
    id: 72,
    image: require('../assets/images/tarot/tarot_f.png'),
    value: require('../assets/images/tarot/72.png'),
    name: 'The Fool',
  },
  {
    id: 73,
    image: require('../assets/images/tarot/tarot_a.png'),
    value: require('../assets/images/tarot/73.png'),
    name: 'The Fool',
  },
  {
    id: 74,
    image: require('../assets/images/tarot/tarot_b.png'),
    value: require('../assets/images/tarot/74.png'),
    name: 'The Fool',
  },
  {
    id: 75,
    image: require('../assets/images/tarot/tarot_c.png'),
    value: require('../assets/images/tarot/75.png'),
    name: 'The Fool',
  },
  {
    id: 76,
    image: require('../assets/images/tarot/tarot_d.png'),
    value: require('../assets/images/tarot/76.png'),
    name: 'The Fool',
  },
  {
    id: 77,
    image: require('../assets/images/tarot/tarot_e.png'),
    value: require('../assets/images/tarot/77.png'),
    name: 'The Fool',
  },
  {
    id: 78,
    image: require('../assets/images/tarot/tarot_f.png'),
    value: require('../assets/images/tarot/78.png'),
    name: 'The Fool',
  },
  {
    id: 79,
    image: require('../assets/images/tarot/tarot_a.png'),
    value: require('../assets/images/tarot/2.png'),
    name: 'The Fool',
  },
  {
    id: 80,
    image: require('../assets/images/tarot/tarot_b.png'),
    value: require('../assets/images/tarot/3.png'),
    name: 'The Fool',
  },
  {
    id: 81,
    image: require('../assets/images/tarot/tarot_c.png'),
    value: require('../assets/images/tarot/4.png'),
    name: 'The Fool',
  },
];
