export const GET_PANCHANG_DATA = 'GET_PANCHANG_DATA'
export const SET_PANCHANG_DATA = 'SET_PANCHANG_DATA'
export const SET_CURRENT_LAT_LONG = 'SET_CURRENT_LAT_LONG'
export const SET_PANCHANG_NEW = 'SET_PANCHANG_NEW';